export const OPEN_CRUD_MODAL = "OPEN_CRUD_MODAL";
export const CLOSE_CRUD_MODAL = "CLOSE_CRUD_MODAL";

export const HTTP_QUERY_STARTED = "HTTP_QUERY_STARTED";

export const HTTP_ADD_KITTEN_RETURNED = "HTTP_ADD_KITTEN_RETURNED";

export const HTTP_GET_KITTENS_STARTED = "HTTP_GET_KITTENS_STARTED";
export const HTTP_GET_KITTENS_RETURNED = "HTTP_GET_KITTENS_RETURNED";

export const HTTP_DELETE_KITTENS_STARTED = "HTTP_DELETE_KITTENS_STARTED";
export const HTTP_DELETE_KITTENS_RETURNED = "HTTP_DELETE_KITTENS_RETURNED";

// Alerts
export const SHOW_ALERT = "SHOW_ALERT";
export const DISMISS_ALERT = "DISMISS_ALERT";
